import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {get} from 'lodash'
import { UsersqueryQuery, useUsersqueryQuery } from '../generated'

const Home: NextPage = () => {

  const {data, error } = useUsersqueryQuery;

  const users = get(
    data,
     "users",
      []
      ) as UsersqueryQuery["users"];

  if (error) return (
    <main className={styles.main}>
        {error.message}
      </main>
  )



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className={styles.main}>
        <h1>List of Users</h1>
        <div>
          {users.map((user) => (
            <div key={user.userId}>
              <p><strong>Email: </strong> {user.email}</p>
              <p><strong>Names: </strong> {user.firstName}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
